### PR TITLE
Add clients Nootti & Nostur

### PR DESCRIPTION
**Pull request by petrikaj**

### CODE REVIEW

**Comment by elidyweaver** [comment]
Thank you @petrikaj for your PR. We'll be reviewing it on this issue: #6 
We're hoping to base the recommendations for the getting started apps on these characteristics: #3

**Comment by elidyweaver** [comment]
@petrikaj is Nootti open source? Is there a repo we could look at?

**Comment by petrikaj** [comment]
@elidyweaver it's not open source.

**Comment by elidyweaver** [comment]
> @elidyweaver it's not open source.

Thank you for your reply. We are adding open source clients to the website.

**Pull request closed without merging**
